create database dml;

use dml;

create table employee(id INT, Name varchar(100),salary INT);

desc employee;

INSERT INTO EMPLOYEE (ID,NAME,SALARY)VALUES(1,"SAI",7000);
INSERT INTO EMPLOYEE VALUES(2,"KUMAR",8000);
INSERT INTO EMPLOYEE VALUES(5000,"PNR",3);
INSERT INTO EMPLOYEE (SALARY,NAME,ID)VALUES(4000,'SAIKUMAR',4);
INSERT INTO EMPLOYEE VALUES(5,'NAME1',2000),(6,'XYZ',3000),(7,'PQR',4000);


SELECT * FROM EMPLOYEE;

CREATE TABLE MAXSAL(ID INT, NAME VARCHAR(30));

INSERT INTO MAXSAL(ID,NAME)SELECT ID,NAME FROM EMPLOYEE;

SELECT * FROM MAXSAL;

INSERT INTO MAXSAL(ID,NAME)SELECT ID,NAME FROM EMPLOYEE WHERE SALARY>='8000';

UPDATE EMPLOYEE SET NAME='PNR' WHERE SALARY=40000; 

SET SQL_SAFE_UPDATES=0;

SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE ID=6;

CREATE TABLE PRODUCTS(
    ID INT ,
    NAME VARCHAR(40) NOT NULL,
    PRICE INT NOT NULL DEFAULT 0
    );
    
    
    INSERT INTO PRODUCTS VALUES (1,'SAI',20000);
    SELECT * FROM PRODUCTS;
    CREATE TABLE LIST1(
    ID INT KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PRICE INT NOT NULL DEFAULT 0);
DESC LIST1;
INSERT INTO LIST1 VALUES (1,"SAI",6000);
INSERT INTO LIST1 (NAME, PRICE) VALUES("XYZ",7000);
INSERT INTO LIST1 (NAME, PRICE) VALUES("ABC",8000);
  SELECT * FROM LIST1;  